
package au.net.electronichealth.ns.smr.tls.v2010;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.3-b01-
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "listError", targetNamespace = "http://ns.electronichealth.net.au/smd/svc/SealedMessageRetrieval/2010")
public class ListErrorMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ListErrorType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ListErrorMsg(String message, ListErrorType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ListErrorMsg(String message, ListErrorType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: au.net.electronichealth.ns.smr.tls.v2010.ListErrorType
     */
    public ListErrorType getFaultInfo() {
        return faultInfo;
    }

}
